### ISSUE TITLE
Package size skyrocketed starting in version 8

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/globby#116]
https://packagephobia.now.sh/result?p=globby

Is there a way to reduce the install size at all?

**Comment by Qix-** [comment]
Looks like `fast-glob` -> `micromatch` -> [`braces`, `extglob`]

**Comment by sindresorhus** [comment]
Yeah, it sucks, but it's unfortunately out of my control. See: https://github.com/mrmlnc/fast-glob/issues/154 Hopefully, it will be fixed soon.
