### ISSUE TITLE
There are still duplicates when using non-normalized paths in patterns

### ISSUE THREAD

**Issue by yannvgn** [sindresorhus/globby#119]
Hi Globby maintainers 👋

I'm having troubles when using non-normalized paths in patterns (like `./file.txt`).

Let's assume the working directory contains the following files: `file1.txt` and `file2.txt`

```js
globby.sync(['*', './file1.txt'])
// returns ['file1.txt', 'file2.txt', './file1.txt']
// where I'm expecting ['file1.txt', 'file2.txt']
```

I just wanted to raise the issue, though I'm not sure if this is an actual bug or if it's wanted.

Cheers

**Comment by mrmlnc** [comment]
Most likely this is related to the `fast-glob` package.  Yeap, it's true.

```js
const fg = require('.');

const entries = fg.sync(['*', './package.json']);

console.log(entries);

```

result

```js
[                     
  './package.json',   
  'LICENSE',          
  'package-lock.json',
  'package.json',     
  'README.md',        
  'test.js',          
  'tsconfig.json',    
  'tslint.json'       
]                     
```

Please, move issue to the `fast-glob` repository.

**Comment by yannvgn** [comment]
Thanks. I've opened an issue in the `fast-glob` repo.
https://github.com/mrmlnc/fast-glob/issues/190

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/mrmlnc/fast-glob/issues/190
