### ISSUE TITLE
globby.sync does not return matching paths with pattern has ( symbol

### ISSUE THREAD

**Issue by tamvanvo** [sindresorhus/globby#122]
I want to get the path of files from directory `C:\Program Files (x86)\Jenkins\workspace\junit\target\surefire-reports` with pattern `C:/Program Files (x86)/Jenkins/workspace/junit/target/surefire-reports/**/*.xml`, but globby sync return empty array.
I found the cause is the pattern has a ( sympbol, so it didn't find the matching paths.
I also tried to other symbols and it worked well e.g -, _.

**Comment by sindresorhus** [comment]
Duplicate of #81
