### ISSUE TITLE
Including @types/glob in dependencies breaks typescript implementations

### ISSUE THREAD

**Issue by StephenLarkin** [sindresorhus/globby#129]
We have a typescript project that uses the [Webfont](https://github.com/itgalaxy/webfont) package to generate our front-end icons. Webfont takes a dependency on your package. This causes `@types/glob` to be included as a dependency, which in turn depends on `@types/node`, which causes our typescript build to break due to the way typescript handles automatic type detection.

The @types/glob dependency should be moved to a devDependency instead.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/del/issues/88. This is a problem with TypeScript or more specifically DefinitelyTyped, not this project specifically.

This will be fixed when https://github.com/sindresorhus/globby/issues/109 is fixed.

**Comment by StephenLarkin** [comment]
The `@types/glob` dependency is surely only used for developing though? The actual globby library surely only uses the javascript output from the typescript files.

I don't understand the reasoning behind including it at all.

**Comment by sindresorhus** [comment]
> The @types/glob dependency is surely only used for developing though?

https://github.com/sindresorhus/globby/blob/4a470444b83882d488eb9c4a1c323896b0fd6c66/index.d.ts#L1
