### ISSUE TITLE
consider micromatch

### ISSUE THREAD

**Issue by tkellen** [sindresorhus/globby#13]
if you get to it before i do:
https://github.com/jonschlinkert/micromatch

**Comment by UltCombo** [comment]
It looks like a very nice project -- I have first heard of it in the glob-stream repository, where it has also been proposed.

Thing is, changing the globbing library is usually a major breaking change, as surely different libs won't cover all the corner/edge cases from one another.

Looks like micromatch is fast and well-tested, perhaps it is worth a try. The main problem is that we are only going to find corner/edge cases once we put it in the road, which I don't personally like.

cc @sindresorhus

**Comment by sindresorhus** [comment]
I'm always open for faster alternatives, but we're only using `multimatch` for ignoring, so not sure how much benefit we'd get. And the downside would be that now the ignoring rules would have different semantics than the normal rules. Which is weird.

**Comment by UltCombo** [comment]
And we wouldn't need any library for ignoring when [this PR](https://github.com/isaacs/node-glob/pull/151) lands on node-glob.

**Comment by sindresorhus** [comment]
That's also true.
