### ISSUE TITLE
Windows globby.sync no longer works for window's paths

### ISSUE THREAD

**Issue by k2snowman69** [sindresorhus/globby#130]
Recently updated from globby@9.2.0 -> globby@10.0.0 and I've found a difference in execution.

Note that this only happens on Windows. It does not happen on OSX or Linux

### 9.2.0
let fileList = sync("d:\Temporary\prettier\src\**\*.js");
// fileList.length === 109

### 10.0.0
let fileList = sync("d:\Temporary\prettier\src\**\*.js");
// fileList.length === 0

Expected:
fileList.length to be 109

**Comment by sindresorhus** [comment]
Duplicate of #127

**Comment by sindresorhus** [comment]
This is mentioned in the release notes: https://github.com/sindresorhus/globby/releases/tag/v10.0.0

**Comment by k2snowman69** [comment]
Where in the release notes? This is all I see:

Breaking:
Upgrade fast-glob package to v3 (#126) 3706920
Important: Read the fast-glob release notes! There are many breaking changes.
Require Node.js 8 9f781ce
Remove **/bower_components/** as a default ignore pattern 2dd76d2

Enhancements:
Add globby.stream() (#113) 8aadde8

Fixes:
Fix using the gitignore and stats options together (#121) 33ca01c

**Comment by k2snowman69** [comment]
Ahh you meant here
https://github.com/mrmlnc/fast-glob#pattern-syntax

**Comment by k2snowman69** [comment]
Closing issue... will have to determine next steps on my own...

**Comment by the-simian** [comment]
If anyone finds this, this is the relevant part: https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows

just using `posix` alone wasn't good enough, because like when I did path.resolve with `__dirname`, it gave me a path with mixed `/` directions on Windows. I had to actually do

`.replace(/\\/g, '/')` on my final path string to get good results... this particular issue really caught me by surprise

**Comment by citrusjunoss** [comment]
> 如果有人发现这个，这是相关的部分：[https](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows)：[//github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows)
> 
> `posix`单独使用是不够好的，因为就像我在做路径时一样`__dirname`，它给了我一条`/`在Windows上带有混合方向的路径。我必须这样做
> 
> `.replace(/\\/g, '/')` 在我的最终路径字符串上取得好成绩......这个特别的问题让我感到惊讶


Can you help me see where there is a problem with usage?

`  const entriesPath = globby.sync([
    path
      .join(process.cwd(), resolveApp('src') + '/containers/*/index.tsx')
      .replace(/\\/g, '/'),
  ]);`

This can't find any matching files

**Comment by citrusjunoss** [comment]
> If anyone finds this, this is the relevant part: https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows
> 
> just using `posix` alone wasn't good enough, because like when I did path.resolve with `__dirname`, it gave me a path with mixed `/` directions on Windows. I had to actually do
> 
> `.replace(/\\/g, '/')` on my final path string to get good results... this particular issue really caught me by surprise

Can you help me see where there is a problem with usage?

const entriesPath = globby.sync([ path .join(process.cwd(), resolveApp('src') + '/containers/*/index.tsx') .replace(/\\/g, '/'), ]);

This can't find any matching files

**Comment by the-simian** [comment]
`'/containers/*/index.tsx'` may need to be `'/containers/**/index.tsx'`

try to glob a specific file first. also you likely want to do the replace on the final path, looks like you've also got like a trailing , and no more glob patterns?

```js
let _path = path .join(process.cwd(), resolveApp('src') + '/containers/*/index.tsx') ;
//console.log(_path)  is this right?? does resolveApp and process.cwd being joined truly work?
_path = _path.replace(/\\/g, '/');
globby.sync(_path);
```

better suggestion? just use the `unixify` package!

```js
var glob = require('globby');
var unixify = require('unixify');

function patternToFile(pattern) {
	let _path = unixify(pattern);
	return glob.sync(_path);
}

let files = patternToFile(`**/**.js`);
```
