### ISSUE TITLE
globby('/*') returns []

### ISSUE THREAD

**Issue by starpit** [sindresorhus/globby#148]
# Actual:

`globby.sync('/*')` returns `[]`

# Expected

Should it not return a list with the files along the same lines as `require('fs').readdirSync('/')`?

**Comment by sindresorhus** [comment]
Might be related to https://github.com/mrmlnc/fast-glob/issues/277

**Comment by starpit** [comment]
nice, thanks for the investigation!

**Comment by starpit** [comment]
This doesn't seem to be a problem any more, at least with `onlyFiles: false`

```javascript
> require('globby').sync('/*', { onlyFiles: false })
[
  '/Applications',
  '/Library',
  '/System',
  '/Users',
  '/Volumes',
  '/bin',
  '/com.apple.TimeMachine.localsnapshots',
  '/cores',
  '/dev',
  '/etc',
  '/home',
  '/opt',
  '/private',
  '/sbin',
  '/tmp',
  '/usr',
  '/var'
]
```
