### ISSUE TITLE
ensureAbsolutePathForCwd method issue

### ISSUE THREAD

**Issue by merickiranoglu** [sindresorhus/globby#153]
Greetings,

I've faced a problem while performing a nuxt generation. I've fixed it for my case, but I felt like I should report this.

cwd is... C:/Documents/ExampleFolder/...
p is...     C:\Documents\ExampleFolder\...

I had to add this line of command to make it work.
cwd = cwd.toString().replace(/\\/gi,'/');

You might wanna check if cwd contains "\\" character, or you will most probably provide a better solution.

**Comment by GerHobbelt** [comment]
related to #155. All paths fed into `globby` should indeed have their directory separators set to UNIX `/` via `.replace(/\\/g, '/')`
