### ISSUE TITLE
Feature request: progress callback

### ISSUE THREAD

**Issue by chris-t-reilly** [sindresorhus/globby#16]
Would you accept a pull request for a final progress callback parameter? This function would be called each time a file or directory is checked for a match, whether the match is successful or not.

**Comment by sindresorhus** [comment]
Why? What do you need it for?

**Comment by chris-t-reilly** [comment]
I have a pipeline processor, and sometimes the glob steps take a while. It would be nice to indicate progress.

**Comment by shinnn** [comment]
Related discussion: https://github.com/sindresorhus/globby/issues/4

Doesn't [glob-stream](https://github.com/wearefractal/glob-stream) meet your requirements?

**Comment by chris-t-reilly** [comment]
@shinnn I suppose I could rewrite my code for use with glob stream, but it's not ideal.

**Comment by UltCombo** [comment]
> This function would be called each time a file or directory is checked for a match, whether the match is successful or not.

glob-stream only emits matched paths, so it wouldn't suffice your specific use case.

**Comment by sindresorhus** [comment]
`glob`, which we use for the globbing part, [doesn't emit an event for every check](https://github.com/isaacs/node-glob#events), so that's not possible. Open a feature request on `glob` if you need this.
