### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by Aymkdn** [sindresorhus/globby#169]
There is a missing argument to the `catch` at https://github.com/sindresorhus/globby/blob/main/index.js#L28

When I run `nexe` or `pkg`, both of them returns the same error due to `globby`:
> SyntaxError: Unexpected token {

I'm using Node v9.9.0, and it needs to be fixed with the below:
```js
	try {
		stat = fs.statSync(options.cwd);
	} catch(e) {
		return;
	}
```

**Comment by sindresorhus** [comment]
You need to upgrade your Node.js version.

**Comment by nick22985** [comment]
Hey,
I am on node version v14.17.3. Npm Version 6.14.14

**Comment by SnehaParanjape-orange** [comment]
I'm using node 16.13.0 and npm 8.1.0 and still seeing this error
