### ISSUE TITLE
Accept `URL` as `options.cwd`?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/globby#176]
```js
import globby from 'globby';
const dir = new URL('./src', import.meta.url);

console.log(await globby('*', {cwd: dir}));

// TypeError: Expected `cwd` to be of type `string` but received type `object`
```

Currently, I have to

```diff
+ import {fileURLToPath} from 'node:url';
  import globby from 'globby';
  const dir = new URL('./src', import.meta.url);

- console.log(await globby('*', {cwd: dir}));
+ console.log(await globby('*', {cwd: fileURLToPath(dir)}));
```

**Comment by sindresorhus** [comment]
Yup. I want to support `URL` anywhere I accept paths.

**Comment by TriMoon** [comment]
@fisker 
>// TypeError: Expected `cwd` to be of type `string` but received type `object`

I was just browsing in this repo and came accross this and wanted to comment.
Not sure how you guys implemented this yet but why not do something like this everywhere a URL is accepted?
```js
if (cwd instanceof URL){
  cwd = cwd.toString()
}
```
eg. check if it is an `URL` object and if so use it's `.toString()` method to convert it into a string...
