### ISSUE TITLE
Should reuse the same cache between calls

### ISSUE THREAD

**Issue by blakeembrey** [sindresorhus/globby#18]
If we're treating this as a single glob, it should be more performant to reuse the cache properties between glob calls. There are `cache`, `statCache`, `symlinks` and `realpathCache` options exposed - https://github.com/isaacs/node-glob#properties.

**Comment by sindresorhus** [comment]
:+1: Good idea!

-

@UltCombo Thoughts?

**Comment by UltCombo** [comment]
@sindresorhus Don't we already pass the options through to node-glob?
I'm not sure if we should implicit cache results -- globby is used far and wide and surely there are places where a check is performed after deletion, so this would be a breaking change.

I believe we should either leave it as is currently (user can pass a `cache` object if they want improved performance), or perhaps we can add a boolean option that does some sorcery behind the scenes. I tend to dislike abstractions that are too magical, though. They tend to lead to hard to debug cases.

More feedback welcome.

**Comment by UltCombo** [comment]
Oh wait a sec, I guess I've misread the issue. You mean to pass the same cache between all calls to node-glob in the **same** globby call? I guess that makes sense. I'll think a bit more.

**Comment by blakeembrey** [comment]
I don't think this would be a breaking. This would only be making things faster, and could simply be implemented by initializing it when the user doesn't pass it in so it doesn't break that.

**Comment by sindresorhus** [comment]
> You mean to pass the same cache between all calls to node-glob in the same globby call?

Yes

**Comment by UltCombo** [comment]
Then :+1: 

Globbing is always subject to race conditions. We can only assume that either there will be no race conditions or, in case they do occur, the user is handling this case correctly.

If we abide by this contract, then there is no problem setting a default cache object for globby calls.

**Comment by sindresorhus** [comment]
Cool. I don't have time to implement this right now, but PR welcome :)

**Comment by gertcuykens** [comment]
https://github.com/isaacs/node-glob/issues/217
maybe @isaacs can also comment on this. Just wanting to make sure all developers are pulling on the same side here :)

**Comment by UltCombo** [comment]
Fixed by #28.
