### ISSUE TITLE
Unknown file extension ".ts" 

### ISSUE THREAD

**Issue by abbasspark** [sindresorhus/globby#183]
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" with 
"typescript": "4.3.5" 
"node": "14.16.0"

**Comment by BarbecueSilver** [comment]
@abbasspark I assume that you also try to update `globby`.


For me adding `--loader ts-node/esm` to the `node` command resolved my issue (e.g.: `node --loader ts-node/esm ./my-script.ts`). 
See the full answer at https://stackoverflow.com/a/66626333/8118803

Check also https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
