### ISSUE TITLE
Nuxt "npm run generate" not working

### ISSUE THREAD

**Issue by Jahongir780110** [sindresorhus/globby#187]
Hi everyone,
I'm a Windows user and when i run "npm run generate" i'm getting the following error:
Error: Path C:/Users/siddi/OneDrive/Рабочий стол/Portfolio/nuxt.config.js is not in cwd C:\Users\siddi\OneDrive\Рабочий стол\Portfolio.

**Comment by sindresorhus** [comment]
This is not related to this package.
