### ISSUE TITLE
`Module '"fast-glob"' has no exported member "Entry"` error when transpiling TypeScript

### ISSUE THREAD

**Issue by kimlimjustin** [sindresorhus/globby#195]
I installed globby as a dependency of the `lerna` dependency on my project and this causing my program to failed transpiling (TS to JS) with the following error:
![image](https://user-images.githubusercontent.com/61906684/134766737-eb6ed47e-69fc-4c19-91c7-d49b5730b6f6.png)

The version of globby here is `11.0.4` (I knew it from opening the package.json from the `node_modules` folder.

Things I tried:
* Installing the latest version of globby but the same error occurred.

**Comment by sindresorhus** [comment]
It's there now at least: https://github.com/mrmlnc/fast-glob/blob/4b71e29a69453931842642fd6b16778c46137a9f/src/index.ts#L17
