### ISSUE TITLE
Consider supporting 10.X

### ISSUE THREAD

**Issue by nmccready** [sindresorhus/globby#199]
Sindre would you consider supporting a 10.X branch to deal with security updates. I would happily submit PRS for them to be published by the original fork. For some libraries it's not worth the extra effort at this point to force an update of 100% ES modules.

**Comment by sindresorhus** [comment]
> For some libraries it's not worth the extra effort at this point to force an update of 100% ES modules.

Being able to update dependencies is a good reason.

**Comment by nmccready** [comment]
Will do 11 sounds great thank you!

**Comment by nmccready** [comment]
@sindresorhus I have a PR ready to be submitted but I need a target branch of 11.X or similar on this repo.

**Comment by nmccready** [comment]
https://github.com/sindresorhus/globby/compare/main...nmccready:main

**Comment by sindresorhus** [comment]
That is not a critical security issue. It's marked as medium (and in reality it's low).

**Comment by sindresorhus** [comment]
I recommend reading https://overreacted.io/npm-audit-broken-by-design/

**Comment by nmccready** [comment]
While agree with all of these sentiments and I have read about npm audit already; this is being flagged by higher level auditing systems at the corporate level like whitesource .  

From companies standpoint it has to be fixed .

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/globby/releases/tag/v11.1.0
