### ISSUE TITLE
provide a `map` function for faster async behavior

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/globby#20]
```js
function handleMatch (individualMatch) {
  // return a promise
}

globby.map([...patterns], handleMatch).then(function (arrayOfPromiseResults)) {

});
```

essentially the equivalent of: 

```js
globby.map([...patterns]).then(function (arrayOfMatches) {
  return Promise.all(arrayOfMatches.map(handleMatch));
});
```

But it provides better async behavior by not requiring you wait for globby to be done before handling a match.

**Comment by sindresorhus** [comment]
What do you need it for? Like, what kind of handling? Unless you're using globbing on a server the sync version is usually faster.

**Comment by UltCombo** [comment]
This seems to be a dupe of #4, though you suggest a different API.

node-glob exposes an [EventEmitter API](https://github.com/isaacs/node-glob#class-globglob). Perhaps we could expose it as well.

For the time being, I'd suggest using [glob-stream](https://github.com/gulpjs/glob-stream) for that use case.

**Comment by jamestalmage** [comment]
Didn't realize sync was faster.

I am scanning the entire Babel codebase multiple times. It's Huge.

Figured out my slowdown was only partially related to globby.

**Comment by sindresorhus** [comment]
The only way to really know is to benchmark. You can almost never guess what's slowing down JS.

**Comment by jamestalmage** [comment]
Well, in this particular case it was me being sloppy.
