### ISSUE TITLE
SyntaxError: require() of ES Module 

### ISSUE THREAD

**Issue by gtraxx** [sindresorhus/globby#245]
Hi, I have a problem compiling less since the update to the new version of node and npm (in order to take into account a new syntax).
Whenever I modify a less file, the compilation returns me the same problem.
How can I solve this problem on macosx ?

`SyntaxError: require() of ES Module /Users/aureliengerits/.npm-global/lib/node_modules/globby/index.js from /Users/aureliengerits/.npm-global/lib/node_modules/lessc/node_modules/less/lib/less-node/plugin-loader.js not supported.
Instead change the require of index.js in /Users/aureliengerits/.npm-global/lib/node_modules/lessc/node_modules/less/lib/less-node/plugin-loader.js to a dynamic import() which is available in all CommonJS modules. in /Users/aureliengerits/.npm-global/lib/node_modules/less-plugin-glob/index.js on line 1, column 15:`

Best Regards
Aurelien

**Comment by sindresorhus** [comment]
Your issue is not related to this package. Open an issue on `less-node` instead.
