### ISSUE TITLE
Error with generateGlobTasks

### ISSUE THREAD

**Issue by nam-edi** [sindresorhus/globby#248]
Hello, I have an error with "generateGlobTasks".

Here is the code that causes the problem:
```
const options = {
			...taskOptions,
			ignore: taskOptions.ignore.concat(ignore)
		};
```

Here is the error: TypeError: Cannot read properties of undefined (reading 'concat')
The problem is solved if we replace it with:
```
const options = {
			...taskOptions,
			ignore: (taskOptions.ignore || []).concat(ignore)
		};

```

**Comment by sindresorhus** [comment]
There's no such code in the latest `globby` version. Make sure you are on the latest version.
