### ISSUE TITLE
ignore is broken when it is not array (regression)

### ISSUE THREAD

**Issue by alexander-akait** [sindresorhus/globby#262]
Code:

```js
import url from "url";
import path from "path";
import { globby } from "globby";

console.log(
  await globby("**/*", {
    followSymbolicLinks: true,
    ignore: "**/index.ejs",
    cwd: path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), "public"),
    objectMode: true,
  }),
);
```

Output:

```
TypeError: directoryPaths.map is not a function
```

Can be fixed using `ignore: ["**/index.ejs"]`, i.e. as array

**Comment by sindresorhus** [comment]
`ignore` is documented to accept an array, so you are using it incorrectly.

https://github.com/mrmlnc/fast-glob#ignore

**Comment by alexander-akait** [comment]
@sindresorhus It works correctly before, for example in v13, and fast-glob supports string and array of strings, but it was not documented, `directoryPaths.map is not a function` inside globby, because it can return string

**Comment by mrmlnc** [comment]
JFYI: https://github.com/mrmlnc/fast-glob/releases/tag/3.3.1

**Comment by sindresorhus** [comment]
> but it was not documented

There are no guarantees when using undocumented behavior.

**Comment by sindresorhus** [comment]
I'm not a big fan of accepting both a `string` and `string[]` in general. It's better to make it simple and always do `string[]` when multiple values are accepted.
