### ISSUE TITLE
globby 14.0.1 breaks bun compatibility

### ISSUE THREAD

**Issue by controversial** [sindresorhus/globby#264]
After updating to 14.0.1, `bun` cannot import `globby`:

<img width="590" alt="Screenshot 2024-02-12 at 5 48 30 PM" src="https://github.com/sindresorhus/globby/assets/10377391/ed033977-6fe6-46d4-adbb-6d09145b07b2">

For Bun users, this is a breaking change in a semver-patch release, but Bun may not be an officially supported platform by this project.

**Comment by controversial** [comment]
The offending import (`getDefaultHighWaterMark`) was added in [merge-streams v2.2.0](https://github.com/sindresorhus/merge-streams/releases/tag/v2.2.0). This is likely primarily an issue for Bun not implementing this function.

**Comment by sindresorhus** [comment]
This should be reported on the Bun issue tracker.

**Comment by controversial** [comment]
Already reported https://github.com/oven-sh/bun/issues/8869

Thanks for the quick response
