### ISSUE TITLE
passing in improper pattern values throws instead of rejecting the promise

### ISSUE THREAD

**Issue by catdad** [sindresorhus/globby#30]
There is no validation on the patterns. It is assumed that they can be used, and the code throws an error if they can't instead of rejecting the promise and triggering the `catch`.

Example:

```javascript
globby([null]).then(...).catch(function(err) {
  // expect error to happen
});
```

This throws [here](https://github.com/sindresorhus/globby/blob/053f03496b3c7d7fe857fb7dfd0530d8b5512705/index.js#L12), where the expectation is that it can read the pattern as a string when it is not a string.

**Comment by UltCombo** [comment]
I'm not entirely sure what are the current best practices regarding invalid inputs. I know synchronous throw in promise APIs is a bad practice, but ideally you shouldn't make a call that you already know that is going to fail.

@sindresorhus Do you agree this exception should be converted to a promise rejection?

**Comment by catdad** [comment]
Yeah, in general, you really shouldn't throw from promises. It breaks some contracts.

As far as making improper calls on purpose, it's kind of a fuzzy area. I have a lib that supports globbing, and I just pass the property directly to `globby`. I think it's a bit silly for me, or anyone else, to have to fully understand globbing in order to support it. I mean, that's the whole purpose of using `globby` in the first place... because I get to do none of the work. But since `globby` needs to actually use the values (my lib never **uses** the value), it should do at least some validation to make sure it can use it. Otherwise, anyone who wants to use `globby` as a dependency would need to understand whether an error would be thrown and why, in order to present a good experience to their own users.

**Comment by catdad** [comment]
And in any event, letting the lib throw "Cannot read property '0' of null" is definitely wrong. The error, however it is conveyed, should be something along the lines of "glob pattern must be a string", since the current error is really not helpful.

**Comment by sindresorhus** [comment]
Yup. We should never ever throw from a promise returning API.

And agree about improving the error message.

**Comment by catdad** [comment]
Just started fixing this, and heads up, I think there is also a bug in `ava`. When I run the tests and some fail, it never runs the `after` to delete the fixture files, causing the tests to fail with an `EEXIST` error next time I run them when trying to create the new fixtures.

**Comment by sindresorhus** [comment]
@catdad That's not a bug. You need to use `after.always()` ;) Would appreciate your thoughts on this issue: https://github.com/avajs/ava/issues/928
