### ISSUE TITLE
.gitattributes settings.

### ISSUE THREAD

**Issue by vivekimsit** [sindresorhus/globby#32]
I got curious about your uses of this file, on further investigation I found some nice post on [SO](http://stackoverflow.com/a/38017715/867461). Please have a look since I find it more reasonable.

**Comment by sindresorhus** [comment]
What is your question?

**Comment by vivekimsit** [comment]
I think it would be good to use:
```

*.txt text
*.html text
*.css text
*.js text
```

wdyt?

**Comment by sindresorhus** [comment]
That is already the default in git. Specifying that would be moot.
