### ISSUE TITLE
Expose glob.hasMagic

### ISSUE THREAD

**Issue by Moeriki** [sindresorhus/globby#35]
Would you mind exposing the `hasMagic` function in globby.

https://github.com/isaacs/node-glob#globhasmagicpattern-options

**Comment by schnittstabil** [comment]
`globby(patterns, [options])` allows `patterns` to be a single `string` or an `array`.
Thus, in my opinion,  `globby.hasMagic` should allow `array` as well.

**Comment by Moeriki** [comment]
How do you see the return value.

`globby.hasMagic(['pattern/**, 'path', 'path'])`

`[true, false, false]` or `true`?

**Comment by kevva** [comment]
Just `true`.
