### ISSUE TITLE
Bump node version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [sindresorhus/globby#37]
If you bump the version to at least node >= 4, you can get rid of the `pinkie-promise` and `object-assign` dependencies.
I would be happy to submit a PR if you would like.

**Comment by sindresorhus** [comment]
No need to open issues on every project. I will update when I'm ready. This project is not yet ready for a major bump.

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry about that.
