### ISSUE TITLE
Incoherent slashes

### ISSUE THREAD

**Issue by guigrpa** [sindresorhus/globby#38]
Why does globby return normalized slashes (/), even for paths with non-ASCII characters in Windows? [According to the slash module](https://github.com/sindresorhus/slash), those paths would not be usable in Windows.

**Comment by sindresorhus** [comment]
Known issue with `node-glob` and should be fixed there: https://github.com/isaacs/node-glob/issues/173

**Comment by guigrpa** [comment]
Thanks for the reference!
