### ISSUE TITLE
"Special" pattern doesn't return files that contains c before ignore chars

### ISSUE THREAD

**Issue by axelssonHakan** [sindresorhus/globby#39]
We have a case there the result doesn't match the expected outcome
It could be a bug in "glob" itself

---test---
```
test( 'glob - async (ignore pattern) ', async t => {
	// Setup
	// fs.mkdirSync( 'tmp' );
	fs.writeFileSync( 'tmp/my.comp.spec.js', 'content' );
	fs.writeFileSync( 'tmp/a.spec.js', 'content' );
	fs.writeFileSync( 'tmp/c.spec.js', 'content' );

	// console.log( await m( 'tmp/*[!.comp].spec.js' ));
	t.deepEqual(await m( 'tmp/*[!.comp].spec.js' ), [ 'tmp/a.spec.js', 'tmp/c.spec.js']);
});
```

**Comment by SamVerschueren** [comment]
I don't think globbing patterns work that way.

```js
await m(['tmp/*.spec.js', '!tmp/*.comp.spec.js'])
```

**Comment by axelssonHakan** [comment]
It should work :-)
It "finds" every other file then the ones that has c. before the ignore pattern.

The test code above returns a.spec.js but not c.spec.js

We are using the grep pattern as CLI input so it would be nice to only be using one pattern instead of several

**Comment by SamVerschueren** [comment]
Oh ok, it wasn't very clear to me what the output was. This module is only a wrapper around [node-glob](https://github.com/isaacs/node-glob) so I'd suggest moving this issue over there. Not much we can do about it here.

**Comment by schnittstabil** [comment]
I believe, it should not work :wink: From the [node-glob](https://github.com/isaacs/node-glob#glob-primer):

> `[...]` Matches a **range of characters**, similar to a RegExp range. If the first character of the range is `!` or `^` then it matches any character not in the range.

Therefore, `[!.comp]` and e.g. `[!po.mc]` should have the same meaning.
