### ISSUE TITLE
How to find a `folder` that are not inside `folder`

### ISSUE THREAD

**Issue by whitecolor** [sindresorhus/globby#41]
The task is to find all `node_modules` in the project tree, that are not inside other node_modules.

I tried unsuccessfully something like:

- `('**/node_modules/', {ignore: '**/node_modules/**/node_modules/'})`

- `('**/node_modules/', {ignore: '**/node_modules/**'})`

Any advice on this?

**Comment by sindresorhus** [comment]
This is not a support forum. http://stackoverflow.com/questions/43718722/glob-find-folder-that-are-not-inside-folder

**Comment by whitecolor** [comment]
I know, could not get an answer there.
