### ISSUE TITLE
maybe? Too slow in big projects

### ISSUE THREAD

**Issue by pixelass** [sindresorhus/globby#43]
I have had issues with big directories and globby.

When globby searches huge directories it takes very long (> 20min) to return results.
In the mentioned comments below I describe the following behavior.

```
proj
  - path/to/code/src (3 directories, 1 level nesting, 20 files)
  - assets (10 directories, 3 level nesting, 100 files)
  - dirt (100 directories, 10 level nesting, 1000 files)
```
```js
globby('path/to/code/src/**/*.js')
// let's wait for 20 mintes
.then(files => {

})
```
I stumbled upon this when using Ava and XO in a big project.

Metions: 
https://github.com/sindresorhus/xo/issues/212#issuecomment-305525741  
https://github.com/avajs/ava/issues/1329#issuecomment-305522620

If more info is needed I will be happy to provide.

**Comment by sindresorhus** [comment]
What operating system and Node.js version? Can you reproduce it with [`glob`](https://github.com/isaacs/node-glob)?

**Comment by pixelass** [comment]
As mentioned this happens when using Ava & XO. See linked comments/issues.

Node version does not matter. I tried several but most recently used LTS (6.11.0).

**Comment by pixelass** [comment]
I changed the issue title for clarity. This is an asumption based on issues that use this package.

**Comment by sindresorhus** [comment]
Just because AVA and XO is slow for you, doesn't mean it's a performance problem with `globby`. Have you actually reproduced it with the example code you provided?

**Comment by pixelass** [comment]
Here's a test with 3 patterns. (only one folder called "frontend" existst in the entire project)
As mentioned before this might not be an issue with globby itself but rather Ava or XO. 

It seems that the specifity of the glob does not have a lot of impact on the speed. I am not sure it if should. The '20 minutes waiting' was something I actually experienced when first running into the issue. ~25 (test results) seconds seems reasonable, I guess.

I will further investegate this and open a better explained issue in Ava/XO. Maybe I can provide a dummy project that reproduces this. 

In my test I noticed that multiple globbys are slower than a single (see last 2 examples with `components`);
I'm not sure how helpful this. I used the following test.

**globbytest.js**  

```js
const globby = require('globby');

const globs = [
	'**/frontend/**/*.js',
	'path/to/brand/**/frontend/**/*.js',
	'path/to/brand/subdir/subdir/frontend/**/*.js'
];

globs.forEach((glob, index) => {
	const then = Date.now();
	globby(glob).then(files => {
		const now = Date.now();
		console.log(`
pattern: ${glob}
time:    ${(now - then) / 1000}
files:   ${files.length}
`);
	}).catch(err => {
		throw err;
	});
});
```

```
$ node globbytest.js 
pattern: path/to/brand/subdir/subdir/frontend/**/*.js
time:    21.837
files:   11831


pattern:  path/to/brand/**/frontend/**/*.js
time:    24.176
files:   11831


pattern: **/frontend/**/*.js
time:    24.536
files:   11831
```


Different patterns (there is no folder called `components`) 

```js
const globs = [
	'**/components/**/*.js',
	'path/to/brand/**/frontend/**/*.js',
	'path/to/brand/subdir/subdir/frontend/**/*.js'
];
```

```
$ node globbytest.js 
pattern: path/to/brand/subdir/subdir/frontend/**/*.js
time:    21.837
files:   11831


pattern:  path/to/brand/**/frontend/**/*.js
time:    24.176
files:   11831


pattern: **/components/**/*.js
time:    21.536
files:   11831
```

```js
const globs = [
	'**/components/**/*.js'
];
```

```
pattern: **/components/**/*.js
time:    11.852
files:   0
```

**Comment by pixelass** [comment]
**Feel free to close.**


I tested this in the mentioned "minimal reproduction".  
The test can be found on a branch called 'globby': https://github.com/pixelass/ava-xo-test/tree/globby

Globby seems to work fine. 

```
pattern: one/a/b/c/d/e/f/g/h/i/j/this-is-it/**/*.js
time:    0.795
files:   53


pattern: one/a/b/c/d/e/f/g/h/**/this-is-it/**/*.js
time:    2.624
files:   53


pattern: one/a/b/c/d/**/this-is-it/**/*.js
time:    16.757
files:   53


pattern: one/a/b/c/**/this-is-it/**/*.js
time:    16.759
files:   53


pattern: **/this-is-it/**/*.js
time:    17.578
files:   53
```
