### ISSUE TITLE
Design idea

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/globby#44]
* ~~[add `expandDirs` option](https://github.com/isaacs/node-glob/issues/344) to "glob"~~
* [add `Globs`](https://github.com/stephenmathieson/node-globs/issues/4) ~~to "globs"~~ **here**
* [add memoized dedupe](https://github.com/stephenmathieson/node-globs/issues/1) ~~to "globs"~~ **here**
* use `Globs` to stream file paths, optionally performing other actions such as filtering [junk](https://npmjs.com/junk)

**Comment by sindresorhus** [comment]
I don't see the point in using the `globs` package. It does exactly the same as `globby`, just less and slower.

**Comment by stevenvachon** [comment]
Its name makes sense for its specific purpose, and offloads that logic so that this package can focus on more than pluralizing.

**Comment by sindresorhus** [comment]
I don't see any benefit of offloading that. Naming is not really a good argument for doing it either.

**Comment by stevenvachon** [comment]
Less code here and for us to test here.

**Comment by sindresorhus** [comment]
I don't modularize just for the sake of it. It should have a clear and large benefit. I see none here. The code here is already coded, tested and battle-proven.

**Comment by stevenvachon** [comment]
Alright, then let's make the above changes in this repo.

**Comment by sindresorhus** [comment]
> except for `expandDirs`.

I have a strong feeling that it will end up being implemented here, as your issue on the `glob` repo will either go unanswered or be declined, but sure, let's give it a try.

**Comment by sindresorhus** [comment]
Most of these optimizations should be implemented in `fast-glob` instead. Please open issues over there for the specific items.
