### ISSUE TITLE
Flip nodir to false if pattern ends with a trailing "/"

### ISSUE THREAD

**Issue by jdalton** [sindresorhus/globby#53]
I noticed in globby 7 that `nodir` is `true` by default. It would be nice if it would auto-flip to `false` if the pattern has a trailing `"/"` which is used to indicate matching directories.

**Comment by sindresorhus** [comment]
I really don't like that pattern. I know it's used by `cp` and some other UNIX tools, but it's very surprising for many users. I never postfix directory paths with `/`, for example.

It's better to be explicit about this. Especially because the patterns could come from a user, and the implementation might not even be able to handle directories. This option should rather explicitly be set by the developer using `globby`. Or better yet, just depend on the `expandDirectories` option and you don't need this at all. Most use-cases only need files, not directories.

**Comment by jdalton** [comment]
I guess my usage is just going in a different direction than globby, v7 at least. For my use I don't want to expand folders and don't want "nodir" enabled. I'm cleaning up build folders and spare files where I delete whole directories at once before running unit tests or publishing. I based the trailing "/" suggestion off of the `nodir` [docs](https://github.com/isaacs/node-glob#options).

> `nodir` Do not match directories, only files. (Note: to match only directories, simply put a / at the end of the pattern.)

**Comment by sindresorhus** [comment]
> I guess my usage is just going in a different direction than globby, v7 at least. For my use I don't want to expand folders and don't want "nodir" enabled.

I'm just optimizing the common case. You can get what you need with `{expandDirectories: false, nodir: false}`.

> I'm cleaning up build folders and spare files where I delete whole directories at once before running unit tests or publishing.

You can't remove directories with Node.js unless they're empty, so it will still need to expand the directories into files, remove the files, and then the directory, even if that happens at a different level.

**Comment by jdalton** [comment]
I'm using fs-extra to remove dirs. Does nodir enabled auto disable expand?

**Comment by sindresorhus** [comment]
`fs-extra` expands directories too: https://github.com/jprichardson/node-fs-extra/blob/f934357bb6a933fc47138e31492b1507bc026ff4/lib/remove/rimraf.js#L63 So it makes no difference if it's done here or in `fs-extra`.

---

> Does nodir enabled auto disable expand?

No, `nodir` enabled is the default. Meaning you will never get any directories. You can still set `nodir: false`, while `expandDirectories: true` if you also want the directory entry. For example, `foo/a`, `foo/b`, but also `foo`, if you do `globby('foo')`.

**Comment by jdalton** [comment]
Oh in this case I'm using trash, but I'm guessing the same applies. I don't care much for what fs-extra or trash are doing internally but I see your point of handling the bare node case by default.
