### ISSUE TITLE
Globby 7.0 gives invalid return when input is array of files

### ISSUE THREAD

**Issue by rasmusbe** [sindresorhus/globby#54]
`globby.sync([ 'test/file-1.php', 'test/file-2.php' ])`

returns:
`[ 'test/file-2.php' ] ` but should return both files

(both file exists)

**Comment by jdalton** [comment]
I've seen this too. One pattern stomps on another. It looks like smth is wonky with how it does the union of results.

**Comment by jdalton** [comment]
It looks like https://github.com/sindresorhus/globby/commit/cf55e5c16f76cf6f6d458fc7e27720d15c0eb1f5 broke it. \@kevva

**Comment by jdalton** [comment]
Though the commit to add the `expandDirectories` feature broke things, disabling `expandDirectories` doesn't fix it. So it effects more than the on code path.

**Comment by jdalton** [comment]
It looks like the `nodir` of `glob` [expands directories](https://github.com/isaacs/node-glob/issues/344) so maybe https://github.com/sindresorhus/globby/commit/cf55e5c16f76cf6f6d458fc7e27720d15c0eb1f5 is at odds with that.

**Comment by sindresorhus** [comment]
> It looks like the nodir of glob expands directories

It does not. Notice how the glob there is `**/*`. Expanding directories means specifying `foo` will result in `foo/**/*`.

**Comment by jdalton** [comment]
Cool. I'm not super familiar with the globby `expandDirectories` stuff. I tried poking at it a bit today without success in fixing the regression.
