### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by I-keep-trying** [sindresorhus/globby#61]
I don't understand what this is supposed to do. At what point do I install and use this? Obviously, I have to create my git repository first, but in what order do I use globby, before my first commit or after? How does this work exactly, within the work flow? I'm using node/npm, with webpack, and vanilla js, and a few other npm packages. I am not using gulp or grunt at this point. 

I was hoping this would take care of the .gitignore problem, giving me a way to easily exclude it from my public github repository. 

Thanks! :)

**Comment by sindresorhus** [comment]
This module is intended to add globbing functionality to other modules and CLI tools and is not intended for end-users.
