### ISSUE TITLE
`expandDirectories` option should also apply to `ignore` patterns 

### ISSUE THREAD

**Issue by pvdlg** [sindresorhus/globby#62]
[expanddirectories](https://github.com/sindresorhus/globby#expanddirectories) applied only on the patterns in the [patterns](https://github.com/sindresorhus/globby#patterns) options. Directories defined in the `ignore` options should be expanded too.

**Comment by bdougherty** [comment]
@pvdlg are you going to try to fix this? If not, I will take a shot at it.

**Comment by pvdlg** [comment]
I was looking at it, but if you'd like to give it a shot, please go ahead.
