### ISSUE TITLE
Directory Expansion 8.X on Windows

### ISSUE THREAD

**Issue by calebboyd** [sindresorhus/globby#70]
I see this passed in CI so it must just be a windows issue only

Running at 5d3d4de

![image](https://user-images.githubusercontent.com/5818726/36136613-062e133a-1057-11e8-98f6-8d24da1eb48f.png)

(expansion is working fine in latest 7.X (pending #63))

**Comment by mrmlnc** [comment]
This is due to a stupid mistake in the `fast-glob` package. I forgot about converting the `\` symbol to UNIX style (`/`) in the patterns.

So, will be fixed today. Sorry for this situation.

**Comment by mrmlnc** [comment]
@sindresorhus, may be you want [set-up](https://github.com/mrmlnc/globby/commit/84bd95f46c761b595b9f082f4534d2ab1f8fdcf9) [AppVeyor](https://www.appveyor.com) for globby?

**Comment by sindresorhus** [comment]
I don't really want 😝, as AppVeyor is annoying to setup and use, and it's flaky, but yes, I'll do it.

**Comment by mrmlnc** [comment]
Fixed by `fast-glob@2.0.4`.
