### ISSUE TITLE
[Feature Request] provide a test function to see if a path is match by target pattern(s)

### ISSUE THREAD

**Issue by e-cloud** [sindresorhus/globby#93]
Assume the future method is called `isMatch(filePath, patterns, options)`

then I want to achieve the follow:
```
globby.isMatch('./package.json', ['src/*.json'])
// return false
```

**Comment by sindresorhus** [comment]
You want https://github.com/sindresorhus/multimatch

**Comment by e-cloud** [comment]
but that lacks the ability to constraints the globs under specified category like `cwd`.

**Comment by sindresorhus** [comment]
You didn't specify that use-case in the issue body. Then I would suggest opening an issue on https://github.com/mrmlnc/fast-glob. Globby doesn't deal directly with the glob patterns. It's just a wrapper around `fast-glob`.

**Comment by e-cloud** [comment]
ok. thanks
